### ISSUE TITLE
Unbundle the Group Header components

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#404] opened 2020-07-24 20:27 UTC
As discussed on a call with @pwalter-ebi and @kasprzyk-sz, it is useful to unbundle the components that make up the Group header.

Proposed actions:

- Current group header remains for legacy support/compatibility
- Make new containers
  - Masthead
  - Navigation (already done)
  - Hero
  - Group information

These could alternatively be done as Gutenberg blocks instead of Containers. I think for editors, they would find Gutenberg blocks more flexible.

**Comment by sturobson** [comment] 2020-07-24 20:30
Is this a dupe of #312? If so, I think we can close #312 because it’s more of a stub and use this issue instead.

**Comment by khawkins98** [comment] 2020-07-24 20:45
Good shut. done

**Comment by kasprzyk-sz** [comment] 2020-08-03 06:52
Done in #411.  

Containers:
- groups header
- navigation
- hero header
- masthead

Blocks:
- hero
- group information

**Closed** 2020-09-17 07:14 UTC
